version: "3"
services:
  app:
    build: .
    restart: always
    expose:
      - 3333
    environment:
      PORT: 3333
      VIRTUAL_HOST: the_url
      VIRTUAL_PORT: "3333"
      LETSENCRYPT_HOST: the_url
      LETSENCRYPT_EMAIL: info@the_url